### ISSUE TITLE
FileNotFoundError: file data/conll-formatted-ontonotes-5.0-12/conll-formatted-ontonotes-5.0/data/train/ not found

### ISSUE THREAD

**Issue by loveJasmine** [swabhs/scaffolding#1]
(.venv) ub16hp@UB16HP:~/ub16_prj/scaffolding$ python -m allennlp.run train training_config/semantic_role_labeler.json --serialization-dir log
2018-12-11 11:08:33,364 - INFO - allennlp.common.params - random_seed = 13370
2018-12-11 11:08:33,364 - INFO - allennlp.common.params - numpy_seed = 1337
2018-12-11 11:08:33,365 - INFO - allennlp.common.params - pytorch_seed = 133
2018-12-11 11:08:33,365 - INFO - allennlp.common.checks - Pytorch version: 0.3.0.post4
2018-12-11 11:08:33,367 - INFO - allennlp.common.params - dataset_reader.type = srl
2018-12-11 11:08:33,367 - INFO - allennlp.common.params - train_data_path = data/conll-formatted-ontonotes-5.0-12/conll-formatted-ontonotes-5.0/data/train/
2018-12-11 11:08:33,367 - INFO - allennlp.commands.train - Reading training data from data/conll-formatted-ontonotes-5.0-12/conll-formatted-ontonotes-5.0/data/train/
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ub16hp/ub16_prj/scaffolding/allennlp/run.py", line 13, in <module>
    main(prog="python -m allennlp.run")
  File "/home/ub16hp/ub16_prj/scaffolding/allennlp/commands/__init__.py", line 81, in main
    args.func(args)
  File "/home/ub16hp/ub16_prj/scaffolding/allennlp/commands/train.py", line 73, in train_model_from_args
    train_model_from_file(args.param_path, args.serialization_dir)
  File "/home/ub16hp/ub16_prj/scaffolding/allennlp/commands/train.py", line 89, in train_model_from_file
    return train_model(params, serialization_dir)
  File "/home/ub16hp/ub16_prj/scaffolding/allennlp/commands/train.py", line 128, in train_model
    train_data = dataset_reader.read(train_data_path)
  File "/home/ub16hp/ub16_prj/scaffolding/allennlp/data/dataset_readers/semantic_role_labeling.py", line 171, in read
    file_path = cached_path(file_path)
  File "/home/ub16hp/ub16_prj/scaffolding/allennlp/common/file_utils.py", line 75, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file data/conll-formatted-ontonotes-5.0-12/conll-formatted-ontonotes-5.0/data/train/ not found
(.venv) ub16hp@UB16HP:~/ub16_prj/scaffolding$

**Comment by swabhs** [comment]
You'll have to get the CoNLL data from the official website: http://conll.cemantix.org/2012/data.html

**Comment by swabhs** [comment]
Or, better still - please use the official OntoNotes data from LDC: https://catalog.ldc.upenn.edu/LDC2013T19
Unfortunately, I cannot share this data due to copyright reasons.
